package main

import "fmt"

var even []int
var sum int

func main() {
	fmt.Println(FibEuleur())
}



func FibEuleur() int {
	var fib [2]int
	fib[0] = 1
	fib[1] = 2
	adding := 3

	for i := 0; adding <= 4000000; i++ {
		adding = fib[0] + fib [1]
		//even = append(even, fib[0])
		even = append(even, fib[1])
		//even([i])=fib[0]
		//even[i+1]=fib[1]
		fib[0] = fib[1]
		fib[1] = adding


	}
	for _, v:= range even{

		if v%2==0{
			sum += v
		}

	}
	return sum
}


/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/